# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for REUSE
#
# See: https://reuse.software/

version = 1
SPDX-PackageName = "tf-tasks"
SPDX-PackageSupplier = "Stuart Ellis <stuart@stuartellis.name>"
SPDX-PackageDownloadLocation = "https://github.com/stuartellis/tf-tasks"

[[annotations]]
path = "CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".copier-*.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".devcontainer/**/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".opentofu-version"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".python-version"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".terraform-version"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tf/contexts/**/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tf/definitions/**/.terraform.lock.hcl"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "template/.terraform-version.jinja"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "template/tf/contexts/**/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "template/tf/templates/context/context.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "uv.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "Stuart Ellis"
SPDX-License-Identifier = "MIT"
